### ISSUE TITLE
Running litestar with "--ssl-certificate" option results in error "No such option: --ssl-certfile"

### ISSUE THREAD

**Issue by pavdwest** [cofin/litestar-granian#29]
E.g. running:

```
litestar --app src.main:app run --reload --port=8000 --host=0.0.0.0 --debug  --ssl-keyfile /etc/certs/project.localhost.key --ssl-certificate /etc/certs/project.localhost.crt --create-self-signed-cert
```

Looks like there's some param name mismatch between what uvivorn is expecting and what is actually passed.

Detailed trace:
```
[+] Running 5/5
 ✔ Container fpsas3-keycloak-database-host-1  Created                                                                                                                           0.0s 
 ✔ Container fpsas3-shared-database-host-1    Created                                                                                                                           0.0s 
 ✔ Container fpsas3-keycloak-1                Created                                                                                                                           0.0s 
 ✔ Container fpsas3-tenant-database-host-1-1  Created                                                                                                                           0.0s 
 ✔ Container fpsas3-backend-1                 Recreated                                                                                                                         0.1s 
Attaching to backend-1
backend-1  | 2024-11-23 18:17:06.853 | INFO     | src.database.service:create_db:169 - Database 'shared-database-host/project_shared' already exists. Nothing to do.
backend-1  | 2024-11-23 18:17:07.011 | WARNING  | src.database.service:_create_models:191 - Syncing models and tables for shared-database-host/project_shared...
backend-1  | 2024-11-23 18:17:07.029 | WARNING  | src.database.service:_create_models:193 - Synced models and tables.
backend-1  | Usage: python -m granian [OPTIONS] APP
backend-1  | Try 'python -m granian --help' for help.
backend-1  | 
backend-1  | Error: No such option: --ssl-certfile (Possible options: --ssl-certificate, --ssl-keyfile, --ssl-keyfile-password)
backend-1  | Granian process stopped.
backend-1  | Traceback (most recent call last):
backend-1  |   File "/opt/venv/bin/litestar", line 8, in <module>
backend-1  |     sys.exit(run_cli())
backend-1  |              ^^^^^^^^^
backend-1  |   File "/opt/venv/lib/python3.12/site-packages/litestar/__main__.py", line 6, in run_cli
backend-1  |     litestar_group()
backend-1  |   File "/opt/venv/lib/python3.12/site-packages/rich_click/rich_command.py", line 367, in __call__
backend-1  |     return super().__call__(*args, **kwargs)
backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/opt/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
backend-1  |     return self.main(*args, **kwargs)
backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/opt/venv/lib/python3.12/site-packages/rich_click/rich_command.py", line 152, in main
backend-1  |     rv = self.invoke(ctx)
backend-1  |          ^^^^^^^^^^^^^^^^
backend-1  |   File "/opt/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
backend-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
backend-1  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/opt/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
backend-1  |     return ctx.invoke(self.callback, **ctx.params)
backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/opt/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
backend-1  |     return __callback(*args, **kwargs)
backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/opt/venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
backend-1  |     return f(get_current_context(), *args, **kwargs)
backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/opt/venv/lib/python3.12/site-packages/litestar/cli/_utils.py", line 254, in wrapped
backend-1  |     return func(*args, **kwargs)
backend-1  |            ^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/opt/venv/lib/python3.12/site-packages/litestar_granian/cli.py", line 363, in run_command
backend-1  |     _run_granian_in_subprocess(
backend-1  |   File "/opt/venv/lib/python3.12/site-packages/litestar_granian/cli.py", line 698, in _run_granian_in_subprocess
backend-1  |     subprocess.run(
backend-1  |   File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
backend-1  |     raise CalledProcessError(retcode, process.args,
backend-1  | subprocess.CalledProcessError: Command '['/opt/venv/bin/python3', '-m', 'granian', 'src.main:app', '--reload', '--host=0.0.0.0', '--port=8000', '--interface=asgi', '--http=auto', '--threads=1', '--workers=1', '--threading-mode=workers', '--blocking-threads=1', '--loop=auto', '--no-opt', '--no-respawn-failed-workers', '--respawn-interval=3.5', '--backlog=1024', '--http1-keep-alive', '--http1-buffer-size=417792', '--no-http1-pipeline-flush', '--ssl-certfile=/etc/certs/project.localhost.crt', '--ssl-keyfile=/etc/certs/project.localhost.key']' returned non-zero exit status 2.
```

**Comment by cofin** [comment]
Closed by #32
